- hosts: web-servers
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - role: common
    - role: iptables
    - role: rbenv
    - role: sendmail
    - role: postgresql/client
    - role: nginx

- hosts: db-servers
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - role: common
    - role: iptables
    - role: postgresql/server
