- name: Install PostgreSQL official yum repository (CentOS 6 x86_64)
  yum: name={{ postgresql_rpm }} state=present

- name: Install PostgreSQL server packages
  yum: name={{ item }} state=present
  with_items:
    - postgresql93
    - postgresql93-server
    - postgresql93-contrib

- name: Initialize PostgreSQL database
  shell: service postgresql-9.3 initdb
         creates=/var/lib/pgsql/9.3/data/postgresql.conf

- name: Install PostgreSQL configuration file
  template: src=postgresql.conf.j2 dest=/var/lib/pgsql/9.3/data/postgresql.conf
            owner=postgres group=postgres mode=0600

- name: Install PostgreSQL client authentication configuration file
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/9.3/data/pg_hba.conf
            owner=postgres group=postgres mode=0600

- name: Start PostgreSQL
  service: name=postgresql-9.3 state=started enabled=yes
